server:
  servlet:
    context-path: /user-management/v1
  port: 9701
spring:
  application:
    name: user-management-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_app_db
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    
    type: com.zaxxer.hikari.HikariDataSource 
    hikari:
      schema: users_data
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

logging:
  file:
    name: logs/application-%d{yyyy-MM-dd}.log
  level:
    '[com.ongraph.usermanagementapp]': debug
    '[org.springframework.web]': debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}- %msg%n"
        
ongraph:
  authentication:
    secretKey: ongraphSecretKey
    tokentExpTimeInMs: 86400000