server:
  servlet:
    context-path: /user-management/v1
  port: 8080
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9093
  application:
    name: user-management-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom_app_db
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
    
    type: com.zaxxer.hikari.HikariDataSource 
    hikari:
      schema: users_data
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
logging:
  file:
    name: logs/application-%d{yyyy-MM-dd}.log
  level:
    '[com.ongraph.usermanagementapp]': info
    '[org.springframework.web]': info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss}- %msg%n"

ongraph:
  authentication:
    secretKey: ongraphSecretKey
    tokenExpTimeInMs: 86400000
  kafka:
    topics:
      registrationEmail: registrationemail
      loginHistory: loginhistory
    emit: false
  