server:
  servlet:
    context-path: /user-management/v1
  port: 8080
spring:
  application:
    name: user-management-service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://postgresql-106852-0.cloudclusters.net:10229/ecom_app_db
    username: ongraphjava
    password: Amit@1234
    driverClassName: org.postgresql.Driver
    
    type: com.zaxxer.hikari.HikariDataSource 
    hikari:
      schema: users_data
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

ongraph:
  authentication:
    secretKey: ongraphSecretKey
    tokentExpTimeInMs: 86400000
  